enum ResponseMessages {
  ACCESS_TOKEN_MISSING = 'Access token is missing or expired',
  INVALID_TOKEN = 'Invalid payload',
  INTERNAL_ERROR = 'Internal server error',
  EMAIL_ALREADY_EXIST = "Email already exists",
  PHONE_ALREADY_EXIST = "Phone number already exists",
  ALL_REQUIRED = "All fields are required",
  PASSWORD_NOT_MATCH = "Passwords do not match",
  USER_REGISTERED = "User Registered",
  INVALID_IDENTIFIER = "Invalid Email or Phone",
  INVALID_PASSWORD = "Invalid Password",
  TOKEN_NOT_CREATED = "couldn't create token",
  USER_LOGIN = "User Logged In",
  USER_LOGOUT = "Logout successful",
  REFRESH_TOKEN_MISSING = "Refresh token missing",
  TOKEN_EXPIRED = "Token Expired",
  TOKEN_REFRESHED = "Tokens refreshed",
  USER_NOT_FOUND = "User not found",
  USER_DATA = "User Data Fetched",
  USER_UPDATED = 'User updated',
  INCORRECT_PASSWORD = "Old password is incorrect",
  CONFIRM_PASSWORD_NOT_MATCH = "New password and confirm password do not match",
  PASSWORD_CHANGED = "Password changed successfully",
  All_CATEGORY_FETCHED = "Fetched All The Category",
  CATEGORY_NOT_FOUND = "Category not found",
  CATEGORY_NAME_REQUIRED = "Name is required",
  CATEGORY_EXIST = "Category already exists",
  CATEGORY_CREATED = "Category Created",
  CATEGORY_DELETED = "Category Deleted",
  CATEGORY_UPDATED = "Category Updated",
  ARTICLE_NOT_FOUND = "Artcle Not Found",
  FETCHED_PREFERED_ARTICLE = "Fetched Prefered Article",
  FETCHED_USER_ARTICLE = "Fetched User Article",
  FETCHED_ARTICLE = " Fetched One Article",
  CONTENT_BLOCK_MUST_ARRAY = "Content blocks must be a non-empty array",
  ARTICLE_ALREADY_EXIST = "An article with this title already exists",
  ARTICLE_CREATED = "Article Created",
  ARTICLE_UPDATED = "Article Updated",
  ARTICLE_DELETED = "Article Deleted",
  CLOUDINARY_FAILED_TO_DELETE = "Failed to delete resource",
  CLOUDINARY_DATA_DELETED = "Success to delete resource"
};

export default ResponseMessages